### ISSUE TITLE
'stk500_recv(): programmer is not responding' problem

### ISSUE THREAD

**Issue by chengkoon** [sayanee/talks#9]
see solution in next comment

edit: see screenshot of problem here:
<img width="1048" alt="screen shot 2017-04-01 at 2 11 01 pm" src="https://cloud.githubusercontent.com/assets/16255377/24575942/348b8c56-16e5-11e7-9b1f-1ccf7d3589ff.png">

**Comment by sayanee** [comment]
try this http://www.ftdichip.com/Drivers/VCP.htm and restart your macbook

**Comment by kelvintyb** [comment]
if the issue is not with the drivers, it's possibly the arduino board so try swapping out your board when uploading the firmware. Root issue is related to the serial port not recognising the arduino board.

**Comment by sayanee** [comment]
closed with https://talks.sayan.ee/web-sensors/#/17 - a separate slide on troubleshooting ports
